# Generated by Django 3.0.3 on 2020-05-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cty',
        ),
    ]
